# Configuração do container para o ambiente (computador) de desenvolvimento

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16 # Usa a imagem oficial do PostgreSQL
    container_name: task-management-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql_pass # Use a mesma senha do seu appsettings
      - POSTGRES_DB=task_management_db
    ports:
      - "5433:5432" # Mapeia a porta 5432 do contêiner para a porta 5433 da sua máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que os dados do banco persistam

  # Serviço da sua API .NET
  api:
    container_name: task-management-api
    build:
      context: . # Constrói a imagem usando o Dockerfile na pasta atual
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Mapeia a porta 8080 do contêiner para a porta 5000 da sua máquina
    environment:
      - ASPNETCORE_URLS=http://+:8080 # Diz à API para rodar na porta 8080 dentro do contêiner
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=task_management_db;Username=postgres;Password=sql_pass
    depends_on:
      - db # Diz ao Docker para iniciar o contêiner 'db' antes do contêiner 'api'

# Define o volume nomeado para persistir os dados do PostgreSQL
volumes:
  postgres_data: